<?xml version="1.0"?>

<robot name="mobile_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="chassisHeight" value="0.1"/>
  <xacro:property name="chassisLength" value="0.4"/>
  <xacro:property name="chassisWidth" value="0.2"/>
  <xacro:property name="chassisMass" value="50"/>

  <xacro:property name="casterRadius" value="0.05"/>
  <xacro:property name="casterMass" value="5"/>

  <xacro:property name="wheelWidth" value="0.05"/>
  <xacro:property name="wheelRadius" value="0.1"/>
  <xacro:property name="wheelPos" value="0.2"/>
  <xacro:property name="wheelMass" value="5"/>

  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.1"/>


  <xacro:include filename="$(find mobile_robot_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find mobile_robot_description)/urdf/macros.xacro" />

  <link name="footprint" />

  <joint name="base_joint" type="fixed">
    <parent link="footprint"/>
    <child link="chassis"/>
  </joint>

  <link name="chassis">
    <collision>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
    </inertial>
  </link>

  <joint name="fixed" type="fixed">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
  </joint>

  <link name="caster_wheel">

    <collision>
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<sphere radius="${casterRadius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.001</mu>
            <mu2>0.001</mu2>
          </ode>
        </friction>
      </surface>         
    </collision>
  
    <visual> 
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <geometry>
	<sphere radius="${casterRadius}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
      <mass value="${casterMass}"/>
      <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
    </inertial>
  </link>


  <wheel lr="left" tY="-1"/>
  <wheel lr="right" tY="1"/>
  
  	<link name="SonarFront_frame">
              <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <box size="0.01 0.01 0.05"/>
                    </geometry>
                    <material name="blue"/>
                </visual>  
        </link>
	<joint name="Sonar/Front_sensor_fixedjoint" type="fixed">
		<parent link="chassis"/>
		<child link="SonarFront_frame"/>
		<origin rpy="0 0.0 0" xyz="0.2 0 0.1"/>
	</joint>

  	<link name="SonarLeft_frame">
              <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <box size="0.01 0.01 0.05"/>
                    </geometry>
                    <material name="blue"/>
                </visual>  
        </link>
	<joint name="Sonar/Left_sensor_fixedjoint" type="fixed">
		<parent link="chassis"/>
		<child link="SonarLeft_frame"/>
		<origin rpy="0 0.0 1.57" xyz="-0.05 0.1 0.1"/>
	</joint>

  	<link name="SonarRight_frame">
              <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <box size="0.01 0.01 0.05"/>
                    </geometry>
                    <material name="blue"/>
                </visual>  
        </link>
	<joint name="Sonar/Right_sensor_fixedjoint" type="fixed">
		<parent link="chassis"/>
		<child link="SonarRight_frame"/>
		<origin rpy="0 0.0 -1.57" xyz="-0.05 -0.1 0.1"/>
	</joint>        
        
    <xacro:include filename="$(find mobile_robot_description)/urdf/mobile_robot.gazebo" />
  
</robot>
